Add solution to 406 | Queue Reconstruction by Height
noisefilter19/LeetCode_Algorithms pull request #41
Opened 2020-10-10 15:15 UTC by jarvisdev

2020-10-10 18:29 UTC, noisefilter19 requested changes

2020-10-10 18:29 UTC, noisefilter19 commented on C++/queue_reconstruction_by_height.cpp
> +            cout<<v[0]<<" "<<v[1]<<endl;
Do we need to print this?

2020-10-10 18:29 UTC, noisefilter19 commented on C++/queue_reconstruction_by_height.cpp
> +                if(ret[i].size()==0 || ret[i][0]==v[0]) {
Is the 2nd condition enough or should we include ret[i][0]>=v[0]? Please add a comment explaining this as well.

2020-10-11 05:47 UTC, jarvisdev commented on C++/queue_reconstruction_by_height.cpp
> +            cout<<v[0]<<" "<<v[1]<<endl;
Nope removing this.

2020-10-11 05:53 UTC, jarvisdev commented on C++/queue_reconstruction_by_height.cpp
> +                if(ret[i].size()==0 || ret[i][0]==v[0]) {
making second condition `>=` would be redundant as we have sorted the array before so in ret array only those pairs will be there which have height <= the height of current pair so we just need to check for == here

2020-10-11 06:00 UTC, noisefilter19 commented on C++/queue_reconstruction_by_height.cpp
> +                if(ret[i].size()==0 || ret[i][0]==v[0]) {
Cool!

2020-10-11 10:24 UTC, noisefilter19 approved these changes

2020-10-11 10:24 UTC, merged