Create Min num of operations to make array equal .
noisefilter19/LeetCode_Algorithms pull request #83
Opened 2020-10-11 07:09 UTC by SushanthReddyManda

2020-10-11 07:09 UTC, SushanthReddyManda commented
Closes #83

2020-10-11 08:57 UTC, SushanthReddyManda commented
Closes #83

2020-10-11 12:09 UTC, noisefilter19 commented on Python/Minimum Operations to Make Array Equal.py
> +            return int(((n-1)*(n+1)/4))
It would be helpful to add how we arrive at this formula

2020-10-11 12:09 UTC, noisefilter19 requested changes
Please make the requested change

2020-10-11 17:18 UTC, SushanthReddyManda commented on Python/Minimum Operations to Make Array Equal.py
> +            return int(((n-1)*(n+1)/4))
Ok i will add it

2020-10-11 17:40 UTC, SushanthReddyManda commented
@noisefilter19  Added Explanation to above code

2020-10-12 15:22 UTC, noisefilter19 approved these changes

2020-10-12 15:22 UTC, merged